services:
  kafka1:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9097:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_LOG_RETENTION_HOURS=1
      - ALLOW_PLAINTEXT_LISTENER=yes

    volumes:
      - ./topic-init.sh:/topic-init.sh
